# Generated by Django 4.0.1 on 2022-11-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registered_vehicles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('idnumber', models.CharField(max_length=12)),
                ('platenumber', models.CharField(max_length=10)),
                ('vehiclemodel', models.CharField(max_length=12)),
                ('imageF', models.ImageField(upload_to='imageF/')),
                ('imageL', models.ImageField(upload_to='imageL/')),
                ('imageR', models.ImageField(upload_to='imageR/')),
                ('imageB', models.ImageField(upload_to='imageB/')),
                ('ORCR', models.ImageField(upload_to='ORCR/')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('idnumber', models.CharField(max_length=12)),
                ('gsfe', models.EmailField(max_length=20)),
                ('Timein', models.TimeField()),
                ('Timeout', models.TimeField()),
                ('withvehicle', models.CharField(max_length=5)),
            ],
        ),
    ]
